apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: somorrostro
      defaultBucket: metales-bucket
      tlsSkipVerify: true
    secureJsonData:
      token: tokenreto0
    editable: true
    isDefault: true