FROM python:3.11-slim

# === Instalar dependencias del sistema y ODBC 18 ===
RUN apt-get update && apt-get install -y \
    curl gnupg2 unixodbc unixodbc-dev apt-transport-https \
    && curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \
    && curl https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# === Instalar dependencias de Python ===
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# === Copiar la aplicación ===
COPY app/ app/

# === Crear carpeta SQL y copiar todos los archivos SQL ===
RUN mkdir -p app/sql
COPY app/sql/ app/sql/

# === Variables de entorno (por si las usas en el futuro) ===
ENV DB_HOST=host.docker.internal
ENV DB_PORT=1433
ENV DB_NAME=Reto-0
ENV DB_USER=docker_user
ENV DB_PASS=docker1234

# === Comando de ejecución ===
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
