version: '3.8'

services:
  metal-prices:
    build: .
    container_name: metal-prices-updater
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid  # Ajusta a tu zona horaria
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - metal-prices-network

networks:
  metal-prices-network:
    driver: bridge