version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
    - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
    - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
    - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
  
  python-app:
    build: .
    container_name: python_app
    depends_on:
      - influxdb
    environment:
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET} 

  grafana:
    image: grafana/grafana:10.3.0
    container_name: grafana_server
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/data
  
  nodered:
    image: nodered/node-red:3.1.1
    container_name: node_red
    depends_on:
      - influxdb
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data

volumes:
  influxdb_data:
  grafana_data:
  nodered_data: