apiVersion: 1

datasources:
  - name: InfluxDB-Flux
    type: influxdb
    access: proxy
    org: ${INFLUX_ORG}
    url: http://influxdb:8086
    jsonData:
      version: 2 # Para usar Flux
      defaultBucket: ${INFLUX_BUCKET}
      organization: ${INFLUX_ORG}
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true