version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_server
    ports:
      - "8087:8086"  # Puerto de InfluxDB
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb2  # Persistencia de datos

