services:
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      - iot-net
  
  python-app:
    build: .
    container_name: python_app
    depends_on:
      - influxdb
    environment:
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET} 
    networks:
      - iot-net

  grafana:
    image: grafana/grafana:10.3.0
    container_name: grafana_server
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      # Volumen para la persistencia de datos de Grafana (ruta corregida)
      - grafana_data:/var/lib/grafana
      # Volúmenes para el aprovisionamiento automático de datasources y dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      # Pasa las variables de InfluxDB para que el aprovisionamiento del datasource funcione
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      # Opcional: Evita la pantalla de cambio de contraseña al primer inicio
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - iot-net
  
  nodered:
    build: ./node_red # Apunta directamente a la carpeta que contiene el Dockerfile y flows.json
    container_name: node_red
    depends_on:
      - influxdb
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    networks:
      - iot-net

volumes:
  influxdb_data:
  grafana_data:
  nodered_data:

networks:
  iot-net:
    driver: bridge